name: tubedownloader # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '1.0.0+1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Download content of yt to watch it offline # 79 char long summary
icon: lib/assets/play_store_512.png
description: |
  Download content of yt to watch it offline

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil