name: tubedownloader 
base: core20 
version: '1.0.0+1' 
summary: Download content of yt to watch it offline # 79 char long summary
icon: lib/assets/play_store_512.png
description: |
  Download content of yt to watch it offline

grade: stable 
confinement: devmode 

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
